version: '3'

services:
  streamlit-app:
    build: ./app
    ports:
      - 8080:8080 
    volumes:
      - ./app:/app
    command: streamlit run main.py --browser.serverAddress="0.0.0.0" --server.port="8080"