version: '3'

services:
  app:
    container_name: fastapi-app
    build: ./app/
    ports:
      - "80:80"
    command: uvicorn app:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    links:
      - db
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/src/ # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'fastapi'
      MYSQL_PASSWORD: 'fastapi'
      MYSQL_DATABASE: 'fastapi'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
volumes:
  db:
    driver: local